# Generated by Django 3.2.5 on 2021-07-23 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0002_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_validator',
        ),
    ]
