# Generated by Django 3.2.5 on 2021-07-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0003_remove_user_is_validator'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirm_delay',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='confirm_retry',
            field=models.IntegerField(default=0),
        ),
    ]
