# Generated by Django 3.2.5 on 2021-07-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0004_auto_20210723_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_delay',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_retry',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_valid',
            field=models.BooleanField(default=False),
        ),
    ]
