# Generated by Django 3.2.7 on 2021-09-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0006_auto_20210910_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersattachments',
            name='photo',
            field=models.ImageField(max_length=255, upload_to='users/'),
        ),
    ]
