# Generated by Django 3.2.7 on 2021-09-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0008_rename_photo_usersattachments_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pseudo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
