# Generated by Django 3.2.7 on 2021-09-25 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0011_contactmessages_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessages',
            name='ip_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
