# Generated by Django 3.2.7 on 2021-10-02 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0014_auto_20211002_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='iso3Code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='isoCode',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phoneCode',
        ),
    ]
