# Generated by Django 3.2.5 on 2021-10-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0016_auto_20211002_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersattachments',
            name='thumb',
            field=models.ImageField(max_length=255, null=True, upload_to='thumb/'),
        ),
    ]
