# Generated by Django 3.2.5 on 2021-11-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0018_connexionsusers_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=255, null=True)),
                ('command', models.CharField(blank=True, max_length=255, null=True)),
                ('id_data', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(blank=True)),
            ],
            options={
                'db_table': 'tb_app_notifications',
            },
        ),
    ]
