# Generated by Django 3.2.5 on 2021-11-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0019_appnotifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='appnotifications',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
