# Generated by Django 3.2.5 on 2021-11-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0020_appnotifications_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='appnotifications',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
