# Generated by Django 3.2.5 on 2021-11-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0024_auto_20211120_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connexionsusers',
            old_name='version',
            new_name='app_version',
        ),
        migrations.AddField(
            model_name='connexionsusers',
            name='os_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
