# Generated by Django 3.2.5 on 2021-11-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0025_auto_20211120_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='appnotifications',
            name='id_msg',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
