# Generated by Django 3.2.5 on 2022-01-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0027_appnotifications_id_sango'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_test',
            field=models.BooleanField(default=False),
        ),
    ]
