# Generated by Django 3.2.5 on 2022-02-07 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0028_user_is_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='network_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
