# Generated by Django 3.2.9 on 2022-08-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0032_user_is_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sexe',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
