# Generated by Django 4.1.3 on 2023-02-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0034_rename_sexe_user_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, null=True, unique=True),
        ),
    ]
