# Generated by Django 4.1.3 on 2023-02-16 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0035_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='reset_delay',
            new_name='reset_at',
        ),
    ]
