# Generated by Django 4.1.3 on 2023-02-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0036_rename_reset_delay_user_reset_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='confirm_delay',
            new_name='confirm_expired_at',
        ),
        migrations.AddField(
            model_name='user',
            name='reset_expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
