# Generated by Django 4.1.3 on 2023-02-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0037_rename_confirm_delay_user_confirm_expired_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_confirmed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reset_valid',
        ),
        migrations.AddField(
            model_name='user',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
