# Generated by Django 4.1.3 on 2023-02-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0038_remove_user_is_confirmed_remove_user_reset_valid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirmed_at',
        ),
        migrations.AddField(
            model_name='user',
            name='reset_code_valid',
            field=models.BooleanField(default=False),
        ),
    ]
