# Generated by Django 4.1.3 on 2023-02-18 21:18

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0040_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='Congo, the Democratic Republic of the', max_length=255, null=True),
        ),
    ]
