# Generated by Django 4.1.3 on 2023-02-18 21:23

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0041_alter_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, default='Congo, the Democratic Republic of the', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='isoCode',
            field=django_countries.fields.CountryField(blank=True, default='CD', max_length=5, null=True),
        ),
    ]
