# Generated by Django 5.2.1 on 2025-05-31 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'tb_client',
            },
        ),
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'tb_sms',
            },
        ),
        migrations.CreateModel(
            name='Smpp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_retour', models.CharField(blank=True, max_length=20, null=True)),
                ('message_id_smsc', models.CharField(blank=True, max_length=100, null=True)),
                ('date_reception_statut', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smpp', to='appbroadcastsms.client')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smpp', to='appbroadcastsms.sms')),
            ],
            options={
                'unique_together': {('client', 'message')},
            },
        ),
    ]
