# Generated by Django 5.2.1 on 2025-06-01 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appbroadcastsms', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='smpp',
            unique_together=set(),
        ),
    ]
