# Generated by Django 5.2.1 on 2025-06-11 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appbroadcastsms', '0002_alter_smpp_unique_together'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='smpp',
            table='tb_broadcastsms',
        ),
    ]
