# Generated by Django 5.2.1 on 2025-06-16 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appbroadcastsms', '0004_alter_smpp_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client',
            table='tb_clients',
        ),
    ]
