# Generated by Django 5.2.1 on 2025-06-16 22:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbroadcastsms', '0005_alter_client_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='smpp',
            name='code_erreur_dlr',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='smpp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smpp',
            name='date_envoi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smpp',
            name='date_livraison',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smpp',
            name='dlr_texte_brut',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smpp',
            name='statut_dlr',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='smpp',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
